### PR TITLE
add contour map section

### PR DESCRIPTION
**Pull request by cnell-usgs**
Initial contributions for another ggplot map exercise. I ended up going a different direction than expected. 

The exercise recreates the same workflow demonstrated previously, but using the elevation and contour APIs. Then I am simply stacking the two, and using the contour alpha channel as a mask for elevation, and using the `scico` library to add a color scale. Then would like to add a data frame with other site coordinates, and encourage participants to try it on their own and share the result. I am building that coordinate list and will enter later. If time seems tight, this part could be skipped to keep moving.

Would love any feedback on this.

### CODE REVIEW

**Comment by mikemahoney218** [comment]
Honestly, looks great! I'm a little concerned for timing on the "on your own" part -- but we can skip it if need be on Friday, and it'll be useful for anyone using the notebook outside the workshop.

Want me to go ahead and merge this as-is, or do you have anything you want to change first? Other than my single punctuation thing (which I can fix myself later today -- I still need to rip out the base raster section) I think this is great as-is.

**Comment by cnell-usgs** [comment]
Let me read through it again today and I'll probably add another commit by the end of the day.

**Comment by cnell-usgs** [comment]
All done here!

**Comment by mikemahoney218** [comment]
LGTM :D

**Pull request merged**
